# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/tests/values/servicemonitor.yaml
metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      # either uncomment this label or patch serviceMonitorSelector in kube-prometheus-stack
      # additionalLabels:
      #   release: "kube-prometheus-stack"
      namespace: monitoring
      metricRelabelings:
        - sourceLabels: [__name__]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik-metrics
      # interval must be > than scrapeTimeout!
      interval: 5s
      scrapeTimeout: 2s
      honorLabels: true
      honorTimestamps: true
      enableHttp2: true
      followRedirects: true
